### ISSUE TITLE
Image on frontpage stretches oddly on changing screen size

### ISSUE THREAD

**Issue by cherrybeans** [cherrybeans/IT2805-Webteknologi-Project#13]

**Comment by hbirchtree** [comment]
Fixed on all browsers except IE and Edge using "object-fit: cover"

**Comment by cherrybeans** [comment]
Still stretches in my tests

![image](https://user-images.githubusercontent.com/25204035/32652562-ee659710-c604-11e7-8ab6-856a766e70a5.png)

![screenshot from 2017-11-10 10-50-27](https://user-images.githubusercontent.com/25204035/32652586-02026924-c605-11e7-8f92-2a6df22d00a9.png)

**Comment by hbirchtree** [comment]
Oops, forgot to commit fix, please re-attempt
