### ISSUE TITLE
On mobile the coverpicture does not stretch to the top

### ISSUE THREAD

**Issue by cherrybeans** [cherrybeans/IT2805-Webteknologi-Project#24]
As shown in this picture (don't look at navigation):

![image](https://user-images.githubusercontent.com/25204035/32652488-b8ec1c9e-c604-11e7-8235-7a04ae756a2d.png)

Easy fix, we can just make the navbar background not transparent on mobile.

**Comment by cherrybeans** [comment]
![screenshot from 2017-11-10 11-27-25](https://user-images.githubusercontent.com/25204035/32654155-840d398a-c60a-11e7-8b86-2156c02fd7e8.png)

**Comment by cherrybeans** [comment]
@voffer10 Care to make the navbar not transparent on mobile?

**Comment by hbirchtree** [comment]
Added media query rule to move the image up when using mobile-sized navbar, now sits flush with top of page
